#!/usr/bin/env python3
"""
Build script for the img site.
Scans an images directory and generates a JavaScript catalog file.

Usage:
    python build.py
    python build.py --img-dir img --output images.js
"""

import argparse
import json
import mimetypes
from pathlib import Path

SUPPORTED_EXTENSIONS = {".gif", ".png", ".jpg", ".jpeg", ".webp", ".svg", ".bmp"}


def main():
    parser = argparse.ArgumentParser(
        description="Generate images.js catalog from an images directory."
    )
    parser.add_argument(
        "--img-dir",
        type=Path,
        default=Path("img"),
        help="Directory containing images (default: img).",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("images.js"),
        help="Output JavaScript file (default: images.js).",
    )
    args = parser.parse_args()

    img_dir = args.img_dir.resolve()
    output_file = args.output.resolve()

    # URL prefix is the relative path from the output file's directory to the images directory.
    try:
        url_prefix = img_dir.relative_to(output_file.parent)
    except ValueError:
        url_prefix = img_dir.name

    images = []

    if img_dir.exists():
        for file_path in sorted(img_dir.iterdir()):
            if file_path.is_file() and file_path.suffix.lower() in SUPPORTED_EXTENSIONS:
                mime, _ = mimetypes.guess_type(str(file_path))
                images.append(
                    {
                        "name": file_path.name,
                        "url": f"{url_prefix}/{file_path.name}",
                        "type": mime or "image/png",
                    }
                )

    js_content = (
        "// Auto-generated by build.py. Do not edit manually.\n"
        f"const IMAGES = {json.dumps(images, indent=2)};\n"
    )

    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(js_content, encoding="utf-8")
    print(f"Generated {output_file} with {len(images)} image(s).")


if __name__ == "__main__":
    main()
